---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  -
    job_name: node
    scheme: https
    metrics_path: /metrics/node
    static_configs:
      -
        targets:
          - allitnils.thgttg.com
          - anjie.thgttg.com
          - badass.nebra.systems
          - bob.thgttg.com
          - caveman.thgttg.com
          - colin.thgttg.com
          - effrafax.thgttg.com
          - expralite.thgttg.com
          - frootmig.thgttg.com
          - gallumbits.thgttg.com
          - golgafrinchans.thgttg.com
          - gramathea.thgttg.com
          - hawalius.thgttg.com
          - krikkit.thgttg.com
          - midgard.v8r.io
          - mitko.thgttg.com
          - novgorodian.thgttg.com
          - poweredge-1.thgttg.com
          - quordlepleen.thgttg.com
          - slartibartfast.thgttg.com
  -
    job_name: geth
    scheme: https
    metrics_path: /metrics/geth
    static_configs:
      -
        targets:
          - bob.thgttg.com
  -
    job_name: nimbus
    scheme: https
    metrics_path: /metrics/nimbus
    static_configs:
      -
        targets:
          - bob.thgttg.com
  #-
  #  job_name: tendermint
  #  scheme: https
  #  metrics_path: /metrics/tendermint
  #  static_configs:
  #    -
  #      targets:
  #        #- celestia.thgttg.com
  #        - lava.v8r.io
  -
    job_name: gpu
    scheme: https
    metrics_path: /metrics/gpu
    static_configs:
      -
        targets:
          - badass.nebra.systems
