---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  -
    job_name: node
    scheme: https
    metrics_path: /metrics/node
    static_configs:
      -
        targets:
          #- celestia.thgttg.com
          - lava.v8r.io
          - badass.nebra.systems
  -
    job_name: tendermint
    scheme: https
    metrics_path: /metrics/tendermint
    static_configs:
      -
        targets:
          #- celestia.thgttg.com
          - lava.v8r.io
  -
    job_name: gpu
    scheme: https
    metrics_path: /metrics/gpu
    static_configs:
      -
        targets:
          - badass.nebra.systems
