---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  -
    job_name: node
    scheme: https
    metrics_path: /metrics/node
    static_configs:
      -
        targets:
          - gnoyager1.v8r.io
          - lava.v8r.io
          - midgard.v8r.io
          - badass.nebra.systems
          - allitnils.thgttg.com
          - colin.thgttg.com
          - gramathea.thgttg.com
          - hawalius.thgttg.com
          - krikkit.thgttg.com
          - mitko.thgttg.com
          - novgorodian.thgttg.com
          - slartibartfast.thgttg.com
  -
    job_name: tendermint
    scheme: https
    metrics_path: /metrics/tendermint
    static_configs:
      -
        targets:
          #- celestia.thgttg.com
          - lava.v8r.io
  -
    job_name: gpu
    scheme: https
    metrics_path: /metrics/gpu
    static_configs:
      -
        targets:
          - badass.nebra.systems
