---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  -
    job_name: thgttg.com - node
    scheme: https
    metrics_path: /metrics/node
    static_configs:
      -
        targets:
          - eddie.thgttg.com
  -
    job_name: thgttg.com - geth
    scheme: https
    metrics_path: /metrics/geth
    static_configs:
      -
        targets:
          - eddie.thgttg.com
