---
server:
  disable: true
positions:
  filename: /tmp/positions.yaml
clients:
  -
    url: https://loki.thgttg.com/loki/api/v1/push
scrape_configs:
  -
    job_name: dendreth
    journal:
      max_age: 12h
      json: false
      labels:
        job: dendreth
    relabel_configs:
      -
        action: keep
        source_labels:
          - __journal__systemd_unit
        regex: (lighthouse-beacon-mainnet|reth-mainnet).service
      -
        source_labels:
          - __journal__systemd_unit
        target_label: service_name
